# =============================================================================
# File        : deno.yml
# Author      : yukimemi
# Last Change : 2025/10/04 20:37:40.
# =============================================================================

name: deno

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        if: matrix.os == 'ubuntu-latest'
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: rhysd/action-setup-vim@19e3dd31a84dbc2c5445d65e9b363f616cab96c1 # v1
        if: matrix.os == 'ubuntu-latest'
        id: vim-rhysd
        with:
          version: "v9.1.2022"
      - uses: thinca/action-setup-vim@48d4eafc4678801eb56149666a1a1e94b54a660e # v1
        if: matrix.os != 'ubuntu-latest'
        id: vim-thinca
        with:
          vim_type: "Vim"
          vim_version: "v9.1.2022"
      - uses: rhysd/action-setup-vim@19e3dd31a84dbc2c5445d65e9b363f616cab96c1 # v1
        id: nvim
        with:
          neovim: true
          version: "v0.11.5"
      - uses: denoland/setup-deno@v2
      - run: deno task ci
        env:
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim-rhysd.outputs.executable || steps.vim-thinca.outputs.executable }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable }}
      - name: Deno outdated
        id: outdated
        if: matrix.os == 'ubuntu-latest'
        run: |
          RESULT=$(deno outdated --update --latest --recursive)
          echo "$RESULT"
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$RESULT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - run: deno task ci
        if: matrix.os == 'ubuntu-latest'
      - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ steps.app-token.outputs.token }}
          labels: automerge
          branch: update/deno-imports
          delete-branch: true
          title: Update Deno imports
          body: |
            Update Deno imports.

            ```
            ${{ steps.outdated.outputs.result }}
            ```

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          commit-message: "chore(deps): Update deno imports"
