# =============================================================================
# File        : deno.yml
# Author      : yukimemi
# Last Change : 2025/10/04 20:37:40.
# =============================================================================

name: deno

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        if: matrix.os == 'ubuntu-latest'
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: stable
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: v0.10.0
      - uses: denoland/setup-deno@v2
      - run: deno task ci
        env:
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable }}
      - run: deno outdated --update --latest --recursive
        if: matrix.os == 'ubuntu-latest'
      - run: deno task ci
        if: matrix.os == 'ubuntu-latest'
      - uses: peter-evans/create-pull-request@v7
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ steps.app-token.outputs.token }}
          labels: automerge
          branch: update/deno-imports
          delete-branch: true
          title: Update Deno imports
          commit-message: "chore(deps): Update deno imports"
