name: update-vim-version

on:
  schedule:
    - cron: "0 0 * * *" # Daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - uses: denoland/setup-deno@v2

      - name: Update Vim/Neovim versions
        id: update-versions
        run: deno run -A scripts/update_vim_version.ts
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          labels: automerge
          commit-message: "chore(ci): update Vim/Neovim versions"
          title: "chore(ci): update Vim/Neovim versions"
          body: |
            Update Vim and Neovim versions in CI workflows.

            ${{ steps.update-versions.outputs.body }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update/vim-version
          delete-branch: true
